export const themes = [
  { id: "classic", name: "Classic", class: "bg-[#fffaf0]" },
  { id: "floating", name: "Floating", class: "bg-gradient-to-br from-pink-100 via-purple-100 to-indigo-100" },
  { id: "grid", name: "Polka grid", class: "bg-[radial-gradient(circle,#fbcfe8_12%,transparent_12%)] bg-[length:28px_28px] bg-[#fdf4ff]" },
  { id: "midnight", name: "Midnight", class: "bg-gradient-to-b from-slate-950 via-indigo-950 to-slate-900 text-slate-100 border-slate-700/50" },
  { id: "sunset", name: "Sunset", class: "bg-gradient-to-br from-amber-200 via-orange-300 to-rose-400" },
  { id: "ocean", name: "Ocean", class: "bg-gradient-to-tl from-cyan-200 via-sky-300 to-blue-500" },
  { id: "forest", name: "Forest", class: "bg-gradient-to-b from-emerald-100 via-green-200 to-teal-300" },
  { id: "lavender", name: "Lavender", class: "bg-gradient-to-br from-violet-100 via-purple-50 to-fuchsia-100" },
  { id: "paper", name: "Craft paper", class: "bg-[#e8dcc8] bg-[linear-gradient(90deg,transparent_79px,#c4b8a8_79px,#c4b8a8_81px,transparent_81px)] bg-[length:100%_100%]" },
  { id: "neon", name: "Neon nights", class: "bg-slate-950 bg-[radial-gradient(ellipse_at_top,_#7c3aed_0%,transparent_50%),radial-gradient(ellipse_at_bottom,_#db2777_0%,transparent_45%)] border-purple-500/30" },
  { id: "mint", name: "Mint fresh", class: "bg-gradient-to-br from-teal-50 via-cyan-100 to-emerald-50" },
  { id: "terracotta", name: "Terracotta", class: "bg-gradient-to-br from-orange-100 via-amber-50 to-stone-200" },
  { id: "arctic", name: "Arctic", class: "bg-gradient-to-b from-slate-100 via-cyan-50 to-blue-100" },
  { id: "gold", name: "Golden hour", class: "bg-gradient-to-br from-yellow-100 via-amber-200 to-orange-200" },
  { id: "cherry", name: "Cherry bloom", class: "bg-gradient-to-b from-pink-50 via-rose-100 to-pink-200" },
  { id: "coffee", name: "Coffee shop", class: "bg-gradient-to-br from-amber-900/90 via-amber-800/85 to-stone-800 text-amber-50 border-amber-900/40" },
  { id: "retro", name: "Retro wave", class: "bg-gradient-to-br from-fuchsia-500 via-purple-600 to-cyan-500 text-white border-white/20" },
  { id: "monochrome", name: "Ink wash", class: "bg-gradient-to-b from-zinc-100 via-zinc-200 to-zinc-300" },
  { id: "starfield", name: "Starfield", class: "bg-slate-950 bg-[radial-gradient(1px_1px_at_20%_30%,white,transparent),radial-gradient(1px_1px_at_60%_70%,white,transparent),radial-gradient(1px_1px_at_50%_50%,#a78bfa,transparent)] bg-[length:100%_100%,100%_100%,200%_200%] text-slate-100 border-violet-500/20" },
  { id: "peach", name: "Peach fuzz", class: "bg-gradient-to-br from-orange-100 via-rose-100 to-amber-50" },
  { id: "slate", name: "Slate studio", class: "bg-gradient-to-br from-slate-200 via-slate-100 to-zinc-200" },
  { id: "aurora", name: "Aurora", class: "bg-gradient-to-tr from-emerald-200 via-teal-200 to-sky-200" },
  { id: "sakura", name: "Sakura", class: "bg-gradient-to-b from-rose-100 via-pink-50 to-amber-50" },
  { id: "candy", name: "Candy", class: "bg-gradient-to-br from-fuchsia-200 via-purple-100 to-cyan-100" },
  { id: "blueprint", name: "Blueprint", class: "bg-gradient-to-b from-sky-50 via-blue-50 to-indigo-100" },
  { id: "strawberry", name: "Strawberry", class: "bg-gradient-to-br from-red-100 via-pink-100 to-amber-50" },
  { id: "tropical", name: "Tropical", class: "bg-gradient-to-br from-green-100 via-teal-100 to-sky-100" },
  { id: "limewash", name: "Limewash", class: "bg-gradient-to-b from-lime-100 via-emerald-100 to-teal-100" },
  { id: "bubblegum", name: "Bubblegum", class: "bg-gradient-to-tr from-pink-100 via-rose-100 to-amber-100" },
  { id: "ember", name: "Ember", class: "bg-gradient-to-br from-orange-200 via-amber-100 to-rose-200" },
  {
    id: "midnight2",
    name: "Midnight Ink",
    class: "bg-gradient-to-b from-zinc-950 via-slate-900 to-stone-950 text-slate-100 border-slate-700/50",
  },
  {
    id: "charcoal",
    name: "Charcoal",
    class: "bg-gradient-to-br from-stone-800 via-zinc-800 to-slate-900 text-zinc-100 border-zinc-700/40",
  },
  {
    id: "galaxy",
    name: "Galaxy",
    class: "bg-slate-950 bg-[radial-gradient(circle_at_20%_20%,#60a5fa_0%,transparent_40%),radial-gradient(circle_at_80%_30%,#a78bfa_0%,transparent_35%),radial-gradient(circle_at_50%_80%,#22c55e_0%,transparent_45%)] text-slate-100 border-violet-500/20",
  },
] as const;

